### ISSUE TITLE
`check-charts-pinned` hook false positive for `OCIRepository` charts

### ISSUE THREAD

**Issue by USA-RedDragon** [gabe565/pre-commit-fluxcd#15]
Given the following example YAML of using a Helm chart backed by an OCI repository, the `check-charts-pinned` hook erroneously marks it as failed:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-etcd
spec:
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts/etcd
  ref:
    semver: "10.6.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: etcd
spec:
  interval: 1m0s
  driftDetection:
    mode: enabled
  releaseName: etcd
  chartRef:
    kind: OCIRepository
    name: bitnami-etcd
```
